 # **DATA CLEANING**

In [1]:
import pandas as pd

df = pd.read_csv('data/insurance_claims.csv')

df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0

In [2]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  object
 1   subscription_length               58592 non-null  float64
 2   vehicle_age                       58592 non-null  float64
 3   customer_age                      58592 non-null  int64
 4   region_code                       58592 non-null  object
 5   region_density                    58592 non-null  int64
 6   segment                           58592 non-null  object
 7   model                             58592 non-null  object
 8   fuel_type                         58592 non-null  object
 9   max_torque                        58592 non-null  object
 10  max_power                         58592 non-null  object
 11  engine_type                       58592 non-null  object
 12  airbags                           58592 non-null  int64
 13  is_esc                            58592 non-null  object
 14  is_adjustable_steering            58592 non-null  object
 15  is_tpms                           58592 non-null  object
 16  is_parking_sensors                58592 non-null  object
 17  is_parking_camera                 58592 non-null  object
 18  rear_brakes_type                  58592 non-null  object
 19  displacement                      58592 non-null  int64
 20  cylinder                          58592 non-null  int64
 21  transmission_type                 58592 non-null  object
 22  steering_type                     58592 non-null  object
 23  turning_radius                    58592 non-null  float64
 24  length                            58592 non-null  int64
 25  width                             58592 non-null  int64
 26  gross_weight                      58592 non-null  int64
 27  is_front_fog_lights               58592 non-null  object
 28  is_rear_window_wiper              58592 non-null  object
 29  is_rear_window_washer             58592 non-null  object
 30  is_rear_window_defogger           58592 non-null  object
 31  is_brake_assist                   58592 non-null  object
 32  is_power_door_locks               58592 non-null  object
 33  is_central_locking                58592 non-null  object
 34  is_power_steering                 58592 non-null  object
 35  is_driver_seat_height_adjustable  58592 non-null  object
 36  is_day_night_rear_view_mirror     58592 non-null  object
 37  is_ecw                            58592 non-null  object
 38  is_speed_alert                    58592 non-null  object
 39  ncap_rating                       58592 non-null  int64
 40  claim_status                      58592 non-null  int64
dtypes: float64(3), int64(10), object(28)
memory usage: 18.3+ MB

In [5]:
df.ffill(inplace=True)

In [7]:
df.columns

Index(['policy_id', 'subscription_length', 'vehicle_age', 'customer_age',
       'region_code', 'region_density', 'segment', 'model', 'fuel_type',
       'max_torque', 'max_power', 'engine_type', 'airbags', 'is_esc',
       'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'steering_type', 'turning_radius', 'length',
       'width', 'gross_weight', 'is_front_fog_lights', 'is_rear_window_wiper',
       'is_rear_window_washer', 'is_rear_window_defogger', 'is_brake_assist',
       'is_power_door_locks', 'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'claim_status'],
      dtype='object')

In [8]:
df['claim_status'].value_counts()

claim_status
0    54844
1     3748
Name: count, dtype: int64

In [9]:
df['fraud_flag'] = df['claim_status']

In [10]:
df[['claim_status', 'fraud_flag']].head()

   claim_status  fraud_flag
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0

In [11]:
df.to_csv('data/cleaned.csv', index=False)

In [13]:
df[['fraud_flag','fraud_flag']].head()

   fraud_flag  fraud_flag
0           0           0
1           0           0
2           0           0
3           0           0
4           0           0

In [14]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,fraud_flag
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,Yes,No,No,No,Yes,0,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,Yes,Yes,Yes,No,No,Yes,Yes,5,0,0